### ISSUE TITLE
Thrift compilation

### ISSUE THREAD

**Issue by adamconnelly** [adamconnelly/Thrift.Net#2]
Implement a Thrift compiler that's capable of producing code compatible with Apache's Thrift runtime library. The Thrift IDL specification can be found [here](https://thrift.apache.org/docs/idl).

- [x] Design and implement a standard error reporting system for compilation errors.
- [x] Report ANTLR syntax errors - #25.
- [x] Support comments - #41.
- [ ] Generate a const - #8.
- [ ] Generate an enum - #9.
- [ ] Generate an Senum - #10.
  - Senum is now deprecated. We may still want to support it, but at a minimum we'll want to provide a warning and discourage use.
- [x] Generate a Struct - #11.
- [x] Generate a Union - #12.
- [ ] Generate an Exception - #13.
- [ ] Generate a Service - #14.
- [x] Add symbol resolution support - #20.
- [ ] Support compiling multiple files - #18.
- [ ] Handle include statements - #19.
- [ ] Documentation Comments - #29.
- [x] Produce a self-contained single executable for different platforms: https://www.hanselman.com/blog/MakingATinyNETCore30EntirelySelfcontainedSingleExecutable.aspx.
