### ISSUE TITLE
Project Management / Open Source Prep

### ISSUE THREAD

**Issue by adam-resdiary** [adamconnelly/Thrift.Net#44]
This is a placeholder task to track any tasks that need to be performed before the project is ready for public adoption, but that aren't related to functionality that the project provides.

- [ ] Setup CI/CD pipelines.
  - [x] Build and run tests against PRs.
  - [ ] Publish nuget packages.
  - [ ] Create GitHub releases.
- [x] Create a contribution guide.
- [ ] Figure out if we need to get contributors to sign a Contributor License Agreement.
- [x] Create a strategy for using GitHub labels.
- [ ] Create issue templates to make reporting problems / requesting new functionality easier.
- [ ] Make sure we have enough documentation.
  - Getting started guides.
  - Documentation about specific configuration / functionality (enabling/disabling linting rules, etc).
  - Guides for contributors (e.g. how to work on the compiler, how to make changes to the library, project structure, testing, etc).
- [ ] Automatically update dependencies using [Dependabot](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically), [Renovate](https://github.com/renovatebot/renovate) or something similar.
- [ ] Come up with a strategy for security disclosures.
